### ISSUE TITLE
Returning a generated Record class only works if using selectFrom

### ISSUE THREAD

**Issue by seanf** [SoylentBob/jooq-mock#2]
I ran into a gotcha when writing my first test with jOOQ Mock. My code under test was using the pattern:

```java
    dsl.select(columnA, columnB, columnC).from(table)...
```

and in my test I was mocking the same `select` of columns, but I made the mistake of returning a generated `Record` class (eg `BookRecord`). 

The result: I found that the columns were being delivered to the code under test in the _wrong order_, and I couldn't understand why, without a debugger and a lot of head scratching.

In general, I think returning a `TableRecord`/`UpdatableRecord` type such as `BookRecord` will only work correctly if the code under test has used this pattern:

```java
    dsl.selectFrom(Tables.BOOK)...
```

whereas if the code under test uses this pattern:

```java
    dsl.select(Tables.BOOK.ID, Tables.BOOK.TITLE, Tables.BOOK.CONTENT_TEXT).from(Tables.BOOK)...
```

it will receive the wrong data, unless the order of columns in the `select` happens to match the field order for the `BookRecord` class. If the column orders don't match, the returned values will be swapped around, thus breaking the code under test.

I did find a few solutions:
1. Change the code under test to use `selectFrom`, just like SqlBooks.java and SqlBooksTest.java. This of course leads to much shorter code all around.
2. Keep the code using `select().from()`, but have the mock return a basic `Record` built with values in the correct order (via `DSLContext.newRecord(Tables.BOOK.ID, Tables.BOOK.TITLE, Tables.BOOK.CONTENT_TEXT).values(...)`)
3. Have the mock build a `BookRecord`, as I did originally, but then converting it to a basic `Record` by calling (`into(...)`), eg `myBookRecord.into(Tables.BOOK.ID, Tables.BOOK.TITLE, Tables.BOOK.CONTENT_TEXT)` (in the correct order)

Do you think anything can be done in the mock API design to protect against this sort of mistake?

Just for reference, the jOOQ Mock test which uses BookRecord with `selectFrom` in the correct way is here:
https://github.com/SoylentBob/jooq-mock/blob/6126a7f62c643325ddbce0a6b7a8d9918476e9ad/src/test/java/com/github/soylentbob/sql/SqlBooksTest.java#L26-L31

**Comment by SoylentBob** [comment]
Thank you for your suggestion, I will look into it as soon as I can.

I haven't really been maintaining this library for a while, but having an active user might get my motivation back up to get the project up to snuff. So thank you for that! :)

**Comment by SoylentBob** [comment]
@seanf please check out the newest commit. I had to introduce a more distinctive method call `whenSelectedFieldsQuery` for this case, it should properly handle the issues you mentioned.

Here's the test that shows how the syntax works:

https://github.com/SoylentBob/jooq-mock/blob/master/src/test/java/com/github/soylentbob/sql/SqlBooksTest.java#L60-87

**Comment by seanf** [comment]
Thanks @SoylentBob! That certainly makes it easier, and simplifies my option 3 above. But what I was really getting at was a way to prevent this pattern from compiling, or at least to have it generate a warning:

```java
dslBuilder.when(dsl
    .select(Tables.BOOK.TITLE, Tables.BOOK.ID).from(Tables.BOOK)
    .where(Tables.BOOK.ID.eq(1))
).thenReturn(preparedBookRecord)
``` 

But it's hard to think of any solution for that, other than replicating a really big chunk of `DSLContext`'s API (`select`, `from` and `selectFrom` plus their overloads) in `MockDSLBuilder`. eg `whenSelectFrom(table)` and `whenSelect(fields...).from(tables...)`. And that's probably not worth it!

Even if the mistake can't be prevented at compile time, it would help have runtime checks, which could fail fast with a helpful message if we call `when`(`select(...).from(...)...`), or even `whenSelectedFieldsQuery`(`selectFrom(table)...`). Would that be feasible, or would it require too much access to jOOQ internals?

**Comment by seanf** [comment]
> Thank you for your suggestion, I will look into it as soon as I can.
> 
> I haven't really been maintaining this library for a while, but having an active user might get my motivation back up to get the project up to snuff. So thank you for that! :)

Hi @SoylentBob,

Thank you for the work you put in. But to let you know, I'm not using `MockDSLBuilder` any more in my project, at least for now. I'm now using Testcontainers to start a Postgres container in Docker (once per VM), and then using jOOQ to insert data at the beginning of each test. For my use case, I find these integration tests more readable and more maintainable than unit tests which mock the exact jOOQ queries with their exact responses.
