### ISSUE TITLE
MockDSLDataProvider seems to ignore parameter bindings

### ISSUE THREAD

**Issue by seanf** [SoylentBob/jooq-mock#4]
The method `com.github.soylentbob.jooq.mock.MockDSLDataProvider#execute` checks the `results` map for a matching SQL statement which has been mocked, but if the SQL is using parameter bindings (eg `where id = ?`), the same `MockResult[]` will be returned regardless of the bindings in `MockExecuteContext`.

**Comment by SoylentBob** [comment]
Yes, you're absolutely right. It was a bit of a pita to find a solution, but I think I was able to resolve this case.

Edit: An example can be found here: https://github.com/SoylentBob/jooq-mock/blob/master/src/test/java/com/github/soylentbob/sql/SqlBooksTest.java#L94
